const page = {
  name: 'page',
  title: 'Pages',
  type: 'document',
  fieldsets: [
    { name: "hero", title: "Hero" },
    { name: "about-me", title: "About me" },
    { name: "SEO", title: "SEO" },
    { name: 'qualifications', title: 'Qualifications' },
    { name: 'textAndImage', title: 'Text and Image' },
    { name: 'benefitsGrid', title: 'Benefits Grid' },
    { name: 'richNumberedList', title: 'Rich Numbered List' },
  ],
  groups: [
    { name: "hero", title: "Hero" },
    { name: "about-me", title: "About me" },
    { name: "SEO", title: "SEO", default: true },
    { name: "settings", title: "Settings" },
    { name: 'qualifications', title: 'Qualifications' },
    { name: 'textAndImage', title: 'Text and Image' },
    { name: 'benefitsGrid', title: 'Benefits Grid' },
    { name: 'richNumberedList', title: 'Rich Numbered List' },
  ],
  fields: [
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      group: "settings",
    },
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      fieldset: "SEO",
      group: "SEO",
    },
    {
      name: 'description',
      title: 'Description',
      type: 'string',
      fieldset: "SEO",
      group: 'SEO',
    },
    {
      name: "homepageHeroImage",
      title: "Hero Image",
      type: "image",
      group: "hero",
      fieldset: "hero",
    },
    {
      name: "homepageHeroLogo",
      title: "Logo",
      type: "image",
      group: "hero",
      fieldset: "hero",
    },
    {
      name: "homepageHeroHeading",
      title: "Heading",
      type: "text",
      group: "hero",
      fieldset: "hero",
    },
    {
      name: 'homepageHeroContent',
      title: 'Content',
      type: 'array',
      of: [{ type: 'block'}],
      group: "hero",
      fieldset: "hero",
    },
    {
      name: "homepageHeroButton",
      title: "Button",
      type: "text",
      group: "hero",
      fieldset: "hero",
    },
    {
      name: "aboutMeTopImage",
      title: "Top Image",
      type: "image",
      group: "about-me",
      fieldset: "about-me",
    },
    {
      name: "aboutMeHeading",
      title: "Heading",
      type: "text",
      group: "about-me",
      fieldset: "about-me",
    },
    {
      name: "aboutMeCaption",
      title: "Caption",
      type: "text",
      group: "about-me",
      fieldset: "about-me",
    },
    {
      name: "aboutMeFirstContentImage",
      title: "First Content Image",
      type: "image",
      group: "about-me",
      fieldset: "about-me",
    },
    {
      name: "aboutMeContent",
      title: "Content",
      type: "text",
      group: "about-me",
      fieldset: "about-me",
    },
    {
      name: "aboutMeSecondContentImage",
      title: "Second Content Image",
      type: "image",
      group: "about-me",
      fieldset: "about-me",
    },
    {
      name: 'qualificationsImage',
      title: 'Image',
      type: 'image',
      group: 'qualifications',
      fieldset: 'qualifications',
    },
    {
      name: 'qualificationsHeading',
      title: 'Heading',
      type: 'string',
      group: 'qualifications',
      fieldset: 'qualifications',
    },
    {
      name: 'qualificationsContent',
      title: 'Content',
      type: 'array',
      of: [{ type: 'qualificationsYear' }],
      group: 'qualifications',
      fieldset: 'qualifications',
    },
    {
      name: 'textAndImageHeading',
      title: 'Heading',
      type: 'string',
      group: 'textAndImage',
      fieldset: 'textAndImage',
    },
    {
      name: 'textAndImageContent',
      title: 'Content',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'textAndImage',
      fieldset: 'textAndImage',
    },
    {
      name: 'textAndImageImage',
      title: 'Image',
      type: 'image',
      group: 'textAndImage',
      fieldset: 'textAndImage',
    },
    {
      name: 'textAndImageList',
      title: 'List of Problems',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'textAndImage',
      fieldset: 'textAndImage',
    },
    {
      name: 'benefitsGridHeading',
      title: 'Heading',
      type: 'string',
      group: 'benefitsGrid',
      fieldset: 'benefitsGrid',
    },
    {
      name: 'benefits',
      title: 'Benefits List',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          {
            name: 'icon',
            title: 'Icon',
            type: 'image', // Use image type
            options: {
              hotspot: true, // Optional, allows for image cropping in Sanity
            },
          },
          {
            name: 'text',
            title: 'Text',
            type: 'string',
          },
        ],
      }],
      group: 'benefitsGrid',
      fieldset: 'benefitsGrid',
    },
    {
      name: 'richNumberedListHeading',
      title: 'Heading',
      type: 'string',
      group: 'richNumberedList',
      fieldset: 'richNumberedList',
    },
    {
      name: 'richNumberedListSections',
      title: 'Sections',
      type: 'array',
      of: [{ type: 'object', fields: [{ name: 'text', title: 'Text', type: 'string' }] }],
      group: 'richNumberedList',
      fieldset: 'richNumberedList',
    },
  ],
}

export default page